package mcpcodegen

import (
	"fmt"
	"log/slog"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
)

func GenerateClient(builder golang.ModuleBuilder, service *gocode.ServiceInterface, outputPackage string) error {
	RequireMCPSDK(builder)

	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	client := &clientArgs{
		Package: pkg,
		Service: service,
		Name:    service.BaseName + "_MCPClient",
		Imports: gogen.NewImports(pkg.Name),
	}

	client.Imports.AddPackages("context", "encoding/json", "errors", "sync", "github.com/modelcontextprotocol/go-sdk/mcp")
	slog.Info(fmt.Sprintf("Generating %v/%v.go", client.Package.PackageName, client.Name))
	outputFile := filepath.Join(client.Package.Path, client.Name+".go")
	return gogen.ExecuteTemplateToFile("MCPClient", clientTemplate, client, outputFile)
}

type clientArgs struct {
	Package golang.PackageInfo
	Service *gocode.ServiceInterface
	Name    string
	Imports *gogen.Imports
}

var clientTemplate = `// DMAS-Forge: Auto-generated by the MCP Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	MCPClient *mcp.Client
	Client *mcp.ClientSession
	mu sync.RWMutex
	ServerAddress string
}

func New_{{.Name}}(ctx context.Context, serverAddress string) (*{{.Name}}, error) {
	c := &{{.Name}}{}
	c.MCPClient = mcp.NewClient(&mcp.Implementation{
		Name:    "{{.Name}}",
		Version: "1.0.0",
	}, nil)
	c.ServerAddress = serverAddress

	session, err := c.connect(ctx)
	if err != nil {
		return nil, err
	}
	c.Client = session
	return c, nil
}

func (mcpclient *{{.Name}}) connect(ctx context.Context) (*mcp.ClientSession, error) {
	return mcpclient.MCPClient.Connect(ctx, &mcp.StreamableClientTransport{Endpoint: "http://" + mcpclient.ServerAddress}, nil)
}

func (mcpclient *{{.Name}}) currentSession() *mcp.ClientSession {
	mcpclient.mu.RLock()
	defer mcpclient.mu.RUnlock()
	return mcpclient.Client
}

func (mcpclient *{{.Name}}) replaceSession(ctx context.Context, stale *mcp.ClientSession) (*mcp.ClientSession, error) {
	mcpclient.mu.Lock()
	defer mcpclient.mu.Unlock()
	if mcpclient.Client != stale {
		return mcpclient.Client, nil
	}
	session, err := mcpclient.connect(ctx)
	if err != nil {
		return nil, err
	}
	mcpclient.Client = session
	if session == nil {
		return nil, errors.New("mcp reconnect returned nil session")
	}
	if stale != nil {
		_ = stale.Close()
	}
	return session, nil
}

func (mcpclient *{{.Name}}) callTool(ctx context.Context, params *mcp.CallToolParams) (*mcp.CallToolResult, error) {
	session := mcpclient.currentSession()
	if session == nil {
		var err error
		session, err = mcpclient.replaceSession(ctx, nil)
		if err != nil {
			return nil, err
		}
	}
	result, err := session.CallTool(ctx, params)
	if err == nil {
		return result, nil
	}

	session, err = mcpclient.replaceSession(ctx, session)
	if err != nil {
		return nil, err
	}
	return session.CallTool(ctx, params)
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{- range $_, $f := .Service.Methods}}
func (mcpclient *{{$receiver}}) {{SignatureWithRetVars $f}} {
	args := make(map[string]any)
	{{range $_, $arg := $f.Arguments}}
	args["{{Title $arg.Name}}"] = {{$arg.Name}}
	{{end}}

	result, err := mcpclient.callTool(ctx, &mcp.CallToolParams{
		Name: "{{$f.Name}}",
		Arguments: args,
	})
	if err != nil {
		return
	}
	if result == nil {
		err = errors.New("mcp returned nil result")
		return
	}
	if result.IsError {
		err = errors.New("mcp tool returned error")
		if len(result.Content) > 0 {
			if content, ok := result.Content[0].(*mcp.TextContent); ok && content.Text != "" {
				err = errors.New(content.Text)
			}
		}
		return
	}
	if len(result.Content) < {{len $f.Returns}} {
		err = errors.New("mcp response had too few content items")
		return
	}

	// Parse the result
	// Each return value corresponds to 1 piece of text content
	{{range $i, $_ := $f.Returns}}
	content_{{$i}}, ok := result.Content[{{$i}}].(*mcp.TextContent)
	if !ok {
		err = errors.New("Currently, only text content is supported!")
	}
	err = json.Unmarshal([]byte(content_{{$i}}.Text), &ret{{$i}})
	if err != nil {
		return
	}
	{{end}}
	return
}
{{end}}
`
