package mcpcodegen

import (
	"fmt"
	"log/slog"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
)

func GenerateClient(builder golang.ModuleBuilder, service *gocode.ServiceInterface, outputPackage string) error {
	RequireMCPSDK(builder)

	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	client := &clientArgs{
		Package: pkg,
		Service: service,
		Name:    service.BaseName + "_MCPClient",
		Imports: gogen.NewImports(pkg.Name),
	}

	client.Imports.AddPackages("context", "encoding/json", "errors", "github.com/modelcontextprotocol/go-sdk/mcp")
	slog.Info(fmt.Sprintf("Generating %v/%v.go", client.Package.PackageName, client.Name))
	outputFile := filepath.Join(client.Package.Path, client.Name+".go")
	return gogen.ExecuteTemplateToFile("MCPClient", clientTemplate, client, outputFile)
}

type clientArgs struct {
	Package golang.PackageInfo
	Service *gocode.ServiceInterface
	Name    string
	Imports *gogen.Imports
}

var clientTemplate = `// DMAS-Forge: Auto-generated by the MCP Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	Client *mcp.ClientSession
	ServerAddress string
}

func New_{{.Name}}(ctx context.Context, serverAddress string) (*{{.Name}}, error) {
	// Create an MCP client.
	client := mcp.NewClient(&mcp.Implementation{
		Name:    "{{.Name}}",
		Version: "1.0.0",
	}, nil)

	session, err := client.Connect(ctx, &mcp.StreamableClientTransport{Endpoint: "http://" + serverAddress}, nil)
	if err != nil {
		return nil, err
	}

	c := &{{.Name}}{}
	c.Client = session
	c.ServerAddress = serverAddress
	return c, nil
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{- range $_, $f := .Service.Methods}}
func (mcpclient *{{$receiver}}) {{SignatureWithRetVars $f}} {
	args := make(map[string]any)
	{{range $_, $arg := $f.Arguments}}
	args["{{Title $arg.Name}}"] = {{$arg.Name}}
	{{end}}

	result, err := mcpclient.Client.CallTool(ctx, &mcp.CallToolParams{
		Name: "{{$f.Name}}",
		Arguments: args,
	})
	if err != nil {
		return
	}

	// Parse the result
	// Each return value corresponds to 1 piece of text content
	{{range $i, $_ := $f.Returns}}
	content_{{$i}}, ok := result.Content[{{$i}}].(*mcp.TextContent)
	if !ok {
		err = errors.New("Currently, only text content is supported!")
	}
	err = json.Unmarshal([]byte(content_{{$i}}.Text), &ret{{$i}})
	if err != nil {
		return
	}
	{{end}}
	return
}
{{end}}
`
