package mcpcodegen

import (
	"fmt"
	"log/slog"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
)

func GenerateServerHandler(builder golang.ModuleBuilder, service *gocode.ServiceInterface, outputPackage string) error {
	RequireMCPSDK(builder)

	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	server := &serverArgs{
		Package: pkg,
		Service: service,
		Name:    service.BaseName + "_MCPServerHandler",
		Imports: gogen.NewImports(pkg.Name),
	}

	server.Imports.AddPackages("context", "net/http", "encoding/json", "github.com/modelcontextprotocol/go-sdk/mcp")

	slog.Info(fmt.Sprintf("Generating %v/%v_MCPServer.go", server.Package.PackageName, service.BaseName))
	outputFile := filepath.Join(server.Package.Path, service.BaseName+"_MCPServer.go")
	return gogen.ExecuteTemplateToFile("MCPServer", serverTemplate, server, outputFile)
}

type serverArgs struct {
	Package golang.PackageInfo
	Service *gocode.ServiceInterface
	Name    string
	Imports *gogen.Imports
}

var serverTemplate = `// DMAS-Forge: Auto-generated by MCP Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	Service {{.Imports.NameOf .Service.UserType}}
	Address string
}

func New_{{.Name}}(ctx context.Context, service {{.Imports.NameOf .Service.UserType}}, serverAddress string) (*{{.Name}}, error) {
	handler := &{{.Name}}{}
	handler.Service = service
	handler.Address = serverAddress
	return handler, nil
}

// DMAS-Forge: Run is called automatically in a separate goruntine
func (handler *{{.Name}}) Run(ctx context.Context) error {
	server := mcp.NewServer(&mcp.Implementation{
		Name:    "{{.Name}}",
		Version: "1.0.0",
	}, nil)

	// Add tools to the server
	{{ range $_, $f := .Service.Methods }}
	mcp.AddTool(server, &mcp.Tool{
		Name: "{{$f.Name}}",
		Description: "",
	}, handler.{{$f.Name}})
	{{end}}

	// Create the streamable HTTP handler.
	http_handler := mcp.NewStreamableHTTPHandler(func(req *http.Request) *mcp.Server {
		return server
	}, nil)

	return http.ListenAndServe(handler.Address, http_handler)
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{ range $_, $f := .Service.Methods }}
type {{$f.Name}}Params struct {
	{{range $_, $arg := $f.Arguments}}
	{{Title $arg.Name}} {{NameOf $arg.Type}}
	{{end}}
}

func (handler *{{$receiver}}) {{$f.Name -}} (mcpCtx context.Context, mcpReq *mcp.CallToolRequest, params *{{$f.Name}}Params) (*mcp.CallToolResult, any, error) {
	{{range $_, $arg := $f.Arguments}}
	{{$arg.Name}} := params.{{Title $arg.Name}}
	{{end}}
	{{RetVars $f "err"}} := handler.Service.{{$f.Name}}({{ArgVars $f "mcpCtx"}})
	if err != nil {
		return nil, nil, err
	}
	response := &mcp.CallToolResult{}
	{{range $i, $_ := $f.Returns}}
	txt_{{$i}}, err := json.Marshal(ret{{$i}})
	if err != nil {
		return nil, nil, err
	}
	cont_{{$i}} := &mcp.TextContent{Text: string(txt_{{$i}})}
	response.Content = append(response.Content, cont_{{$i}})
	{{end}}
	return response, nil, nil
}
{{end}}
`
