package a2acodegen

import (
	"fmt"
	"log/slog"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
)

// This function is used by the A2A plugin to generate the client-side A2A service
func GenerateClient(builder golang.ModuleBuilder, service *gocode.ServiceInterface, outputPackage string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	client := &clientArgs{
		Package: pkg,
		Service: service,
		Name:    service.BaseName + "_A2AClient",
		Imports: gogen.NewImports(pkg.Name),
	}

	client.Imports.AddPackages(
		"encoding/json", "context", "errors", "trpc.group/trpc-go/trpc-a2a-go/client", "trpc.group/trpc-go/trpc-a2a-go/protocol",
	)

	slog.Info(fmt.Sprintf("Generating %v/%v.go", client.Package.PackageName, client.Name))
	outputFile := filepath.Join(client.Package.Path, client.Name+".go")
	return gogen.ExecuteTemplateToFile("A2AClient", clientTemplate, client, outputFile)
}

// Arguments to the template code
type clientArgs struct {
	Package golang.PackageInfo
	Service *gocode.ServiceInterface
	Name    string
	Imports *gogen.Imports
}

var clientTemplate = `// DMAS-Forge: Auto-generated by the A2A Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	Client *client.A2AClient
	ServerAddress string
}

func New_{{.Name}}(ctx context.Context, serverAddress string) (*{{.Name}}, error) {
	var err error
	c := &{{.Name}}{}
	c.ServerAddress = "http://" + serverAddress
	c.Client, err = client.NewA2AClient(c.ServerAddress)
	if err != nil {
		return nil, err
	}
	return c, nil
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{- range $_, $f := .Service.Methods }}
func (a2aclient *{{$receiver}}) {{SignatureWithRetVars $f}} {
	vals := make(map[string]string)
	{{range $_, $arg := $f.Arguments}}
	{{if eq (NameOf $arg.Type) "string" -}}
	vals["{{$arg.Name}}"] = {{$arg.Name}}
	{{- else -}}
	bytes_{{$arg.Name}}, err := json.Marshal({{$arg.Name}})
	if err != nil {
		return
	}
	vals["{{$arg.Name}}"] = string(bytes_{{$arg.Name}})
	{{- end}}
	{{end}}
	vals["a2a_task_methodname"] = "{{$f.Name}}"

	req_bytes, err := json.Marshal(vals)
	if err != nil {
		return
	}
	input := string(req_bytes)
	contextID := protocol.GenerateContextID()

	message := protocol.NewMessageWithContext(
		protocol.MessageRoleUser,
		[]protocol.Part{protocol.NewTextPart(input)},
		nil, // taskID
		&contextID,
	)

	message_params := protocol.SendMessageParams{
		Message: message,
	}

	result, err := a2aclient.Client.SendMessage(ctx, message_params)
	if err != nil {
		return
	}

	response := struct {
		{{range $i, $arg := $f.Returns}}
		Ret{{$i}} {{NameOf $arg.Type}}
		{{end}}
	}{}

	switch resp := result.Result.(type) {
	case *protocol.Message:
		text_part, ok := resp.Parts[0].(*protocol.TextPart)
		if !ok {
			err = errors.New("First part should be a text part")
			return
		}
		resp_bytes := []byte(text_part.Text)
		err = json.Unmarshal(resp_bytes, &response)
		if err != nil {
			return
		}
		{{range $i, $arg := $f.Returns}}
		ret{{$i}} = response.Ret{{$i}}
		{{end}}
	default:
		err = errors.New("Unsupported result type from A2A server")
	}
	return
}
{{end}}
`
