package a2acodegen

import (
	"fmt"
	"log/slog"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
)

/*
This function is used by the HTTP plugin to generate the server-side HTTP service.
*/
func GenerateServerHandler(builder golang.ModuleBuilder, service *gocode.ServiceInterface, outputPackage string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	server := &serverArgs{
		Package: pkg,
		Service: service,
		Name:    service.BaseName + "_A2AServerHandler",
		Imports: gogen.NewImports(pkg.Name),
	}

	server.Imports.AddPackages("context", "encoding/json", "errors", "trpc.group/trpc-go/trpc-a2a-go/server", "trpc.group/trpc-go/trpc-a2a-go/taskmanager", "trpc.group/trpc-go/trpc-a2a-go/protocol")

	slog.Info(fmt.Sprintf("Generating %v/%v_A2AServer.go", server.Package.PackageName, service.BaseName))
	outputFile := filepath.Join(server.Package.Path, service.BaseName+"_A2AServer.go")
	return gogen.ExecuteTemplateToFile("A2AServer", serverTemplate, server, outputFile)
}

/*
Arguments to the template code
*/
type serverArgs struct {
	Package golang.PackageInfo
	Service *gocode.ServiceInterface
	Name    string         // Name of the generated wrapper class
	Imports *gogen.Imports // Manages imports for us
}

var serverTemplate = `// Blueprint: Auto-generated by HTTP Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	Service {{.Imports.NameOf .Service.UserType}}
	Address string
}

func New_{{.Name}}(ctx context.Context, service {{.Imports.NameOf .Service.UserType}}, serverAddress string) (*{{.Name}}, error) {
	handler := &{{.Name}}{}
	handler.Service = service
	handler.Address = serverAddress
	return handler, nil
}

// Blueprint: Run is called automatically in a separate goroutine by runtime/plugins/golang/di.go
func (handler *{{.Name}}) Run(ctx context.Context) error {
	bool_val := false
	desc := "Skill supported by A2A agent"
	agentCard := server.AgentCard{
		Name: "{{.Name}}",
		Description: "A2A Agent enabled with Blueprint",
		URL: handler.Address,
		Version: "2.0.0",
		Provider: &server.AgentProvider{
			Organization: "Blueprint Uservices",
		},
		Capabilities: server.AgentCapabilities{
			Streaming:              &bool_val,
			PushNotifications:      &bool_val,
			StateTransitionHistory: &bool_val,
		},
		DefaultInputModes:  []string{"text"},
		DefaultOutputModes: []string{"text"},
		Skills: []server.AgentSkill{
			{{range $_, $f := .Service.Methods}}
			{
				ID: "{{$f.Name}}",
				Name: "{{$f.Name}}",
				Description: &desc,
				Tags: []string{"text", "{{$f.Name}}"},
				InputModes:  []string{"text"},
				OutputModes: []string{"text"},
				Examples: []string{},
			},
			{{end}}
		},
	}

	baseTaskManager, err := taskmanager.NewMemoryTaskManager(handler)
	if err != nil {
		return err
	}
	srv, err := server.NewA2AServer(agentCard, baseTaskManager, server.WithCORSEnabled(true))
	if err != nil {
		return err
	}
	return srv.Start(handler.Address)
}

func (handler *{{.Name}}) ProcessMessage(ctx context.Context, message protocol.Message, options taskmanager.ProcessOptions, taskHandler taskmanager.TaskHandler) (*taskmanager.MessageProcessingResult, error) {
	txt_part, ok := message.Parts[0].(*protocol.TextPart)
	if !ok {
		return nil, errors.New("This implementation only expects 1 text part")
	}
	bytes := []byte(txt_part.Text)
	// Unmarshal the bytes into a map[string][string]
	var m map[string]string
	err := json.Unmarshal(bytes, &m)
	if err != nil {
		return nil, errors.New("Unable to unmarshal the json struct")
	}
	method_name := m["a2a_task_methodname"]
	{{ range $_, $f := .Service.Methods}}
	if method_name == "{{$f.Name}}" {
		return handler.{{$f.Name}}(ctx, m)
	}
	{{end}}
	return nil, errors.New("Unknown skill selected " + method_name)
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{ range $_, $f := .Service.Methods }}
func (handler *{{$receiver}}) {{$f.Name -}} (ctx context.Context, m map[string]string)(*taskmanager.MessageProcessingResult, error) {
	{{range $_, $arg := $f.Arguments}}
	{{if eq (NameOf $arg.Type) "string" -}}
	{{$arg.Name}}, ok := m["{{$arg.Name}}"]
	if !ok {
		return nil, errors.New("Unable to find argument with name {{$arg.Name}}")
	}
	{{- else -}}
	request_{{$arg.Name}}, ok := m["{{$arg.Name}}"]
	if !ok {
		return nil, errors.New("Unable to find argument with name {{$arg.Name}}")
	}
	var {{$arg.Name}} {{NameOf $arg.Type}}
	if request_{{$arg.Name}} != "" {
		err := json.Unmarshal([]byte(request_{{$arg.Name}}), &{{$arg.Name}})
		if err != nil {
			return nil, err
		}
	}
	{{- end}}
	{{end}}
	{{RetVars $f "err"}} {{HasNewReturnVars $f}} handler.Service.{{$f.Name}}({{ArgVars $f "ctx"}})
	if err != nil {
		return nil, err
	}
	response := struct {
		{{range $i, $arg := $f.Returns}}
		Ret{{$i}} {{NameOf $arg.Type}}
		{{end}}
	}{}
	{{range $i, $arg := $f.Returns}}
	response.Ret{{$i}} = ret{{$i}}
	{{end}}
	resp_bytes, err := json.Marshal(response)
	if err != nil {
		return nil, err
	}
	msg := protocol.NewMessage(protocol.MessageRoleAgent, []protocol.Part{protocol.NewTextPart(string(resp_bytes))})
	return &taskmanager.MessageProcessingResult{
		Result: &msg,
	}, nil	
}
{{end}}
`
